<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="xiebeibeideMacBook-Pro.local" ignored="0" name="用户管理系统测试用例" tests="7" failures="3" timestamp="14 六月 2019 15:18:06 GMT" time="26.17" errors="0">
  <testcase name="loginTrue" time="0.774" classname="com.course.cases.LoginTest"/>
  <testcase name="loginFalse" time="0.041" classname="com.course.cases.LoginTest"/>
  <testcase name="addUser" time="5.066" classname="com.course.cases.AddUserTest"/>
  <testcase name="getUserInfo" time="0.052" classname="com.course.cases.GetUserInfoTest"/>
  <testcase name="updateUserInfo" time="10.036" classname="com.course.cases.UpdateUserInfoTest">
    <failure type="org.apache.ibatis.exceptions.PersistenceException" message="
### Error querying database.  Cause: java.lang.IllegalArgumentException: Mapped Statements collection does not contain value for null
### Cause: java.lang.IllegalArgumentException: Mapped Statements collection does not contain value for null">
      <![CDATA[org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: java.lang.IllegalArgumentException: Mapped Statements collection does not contain value for null
### Cause: java.lang.IllegalArgumentException: Mapped Statements collection does not contain value for null
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:77)
	at com.course.cases.UpdateUserInfoTest.updateUserInfo(UpdateUserInfoTest.java:28)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Mapped Statements collection does not contain value for null
	at org.apache.ibatis.session.Configuration$StrictMap.get(Configuration.java:875)
	at org.apache.ibatis.session.Configuration.getMappedStatement(Configuration.java:708)
	at org.apache.ibatis.session.Configuration.getMappedStatement(Configuration.java:701)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	... 37 more
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- updateUserInfo -->
  <testcase name="deleteUser" time="10.061" classname="com.course.cases.UpdateUserInfoTest">
    <failure type="java.lang.NumberFormatException" message="For input string: &amp;quot;{&amp;quot;timestamp&amp;quot;:1560525476198,&amp;quot;status&amp;quot;:500,&amp;quot;error&amp;quot;:&amp;quot;Internal Server Error&amp;quot;,&amp;quot;exception&amp;quot;:&amp;quot;org.springframework.jdbc.BadSqlGrammarException&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;\n### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near &amp;apos;where id = 8&amp;apos; at line 3\n### The error may involve com.course.updateUserInfo-Inline\n### The error occurred while setting parameters\n### SQL: update user                    where id = ?\n### Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near &amp;apos;where id = 8&amp;apos; at line 3\n; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near &amp;apos;where id = 8&amp;apos; at line 3&amp;quot;,&amp;quot;path&amp;quot;:&amp;quot;/v1/updateUserInfo&amp;quot;}&amp;quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: "{"timestamp":1560525476198,"status":500,"error":"Internal Server Error","exception":"org.springframework.jdbc.BadSqlGrammarException","message":"\n### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where id = 8' at line 3\n### The error may involve com.course.updateUserInfo-Inline\n### The error occurred while setting parameters\n### SQL: update user                    where id = ?\n### Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where id = 8' at line 3\n; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where id = 8' at line 3","path":"/v1/updateUserInfo"}"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.course.cases.UpdateUserInfoTest.getResult(UpdateUserInfoTest.java:73)
	at com.course.cases.UpdateUserInfoTest.deleteUser(UpdateUserInfoTest.java:44)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- deleteUser -->
  <testcase name="getUserListInfo" time="0.066" classname="com.course.cases.GetUserInfoListTest">
    <failure type="java.lang.AssertionError" message="expected [{&amp;quot;password&amp;quot;:&amp;quot;zhaozhao&amp;quot;,&amp;quot;sex&amp;quot;:&amp;quot;0&amp;quot;,&amp;quot;permission&amp;quot;:&amp;quot;1&amp;quot;,&amp;quot;id&amp;quot;:8,&amp;quot;userName&amp;quot;:&amp;quot;zhao9&amp;quot;,&amp;quot;age&amp;quot;:&amp;quot;35&amp;quot;}] but found [{&amp;quot;password&amp;quot;:&amp;quot;zhaozhao&amp;quot;,&amp;quot;isDelete&amp;quot;:null,&amp;quot;sex&amp;quot;:&amp;quot;0&amp;quot;,&amp;quot;permission&amp;quot;:&amp;quot;1&amp;quot;,&amp;quot;id&amp;quot;:8,&amp;quot;userName&amp;quot;:&amp;quot;zhao9&amp;quot;,&amp;quot;age&amp;quot;:&amp;quot;35&amp;quot;}]">
      <![CDATA[java.lang.AssertionError: expected [{"password":"zhaozhao","sex":"0","permission":"1","id":8,"userName":"zhao9","age":"35"}] but found [{"password":"zhaozhao","isDelete":null,"sex":"0","permission":"1","id":8,"userName":"zhao9","age":"35"}]
	at com.course.cases.GetUserInfoListTest.getUserListInfo(GetUserInfoListTest.java:43)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- getUserListInfo -->
</testsuite> <!-- 用户管理系统测试用例 -->
